### ISSUE TITLE
ValueError: Cannot mix tz-aware with tz-naive values

### ISSUE THREAD

**Issue by dancohenenterprise** [JerBouma/ThePassiveInvestor#14]
pi.create_ETF_report(['VOO'], 'Popular ETFs.xlsx')
D:\code\pycash\venv\Lib\site-packages\yahooquery\utils\__init__.py:1470: FutureWarning: 'S' is deprecated and will be removed in a future version. Please use 's' instead of 'S'.
  has_live_indice = index_utc[-1] >= last_trade - pd.Timedelta(2, "S")
D:\code\pycash\venv\Lib\site-packages\yahooquery\ticker.py:1333: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
  df["dividends"].fillna(0, inplace=True)
Traceback (most recent call last):
  File "C:\Users\cohend\AppData\Local\JetBrains\PyCharm Community Edition 2023.1.1\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "D:\code\pycash\venv\Lib\site-packages\thepassiveinvestor\create_report.py", line 49, in create_ETF_report
    stock_data.index = pd.to_datetime(stock_data.index)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\pycash\venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 1076, in to_datetime
    result = convert_listlike(arg, format, name=arg.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\pycash\venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 435, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\pycash\venv\Lib\site-packages\pandas\core\arrays\datetimes.py", line 2398, in objects_to_datetime64
    result, tz_parsed = tslib.array_to_datetime(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "tslib.pyx", line 414, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 630, in pandas._libs.tslib.array_to_datetime
ValueError: Cannot mix tz-aware with tz-naive values

**Comment by JerBouma** [comment]
I can not reproduce this, make sure you have the correct Pandas and Python versions as listed in the requirements.

<img width="692" alt="image" src="https://github.com/JerBouma/ThePassiveInvestor/assets/46355364/5840eafb-4ab7-48a6-ab69-66f5747c2942">
